### ISSUE TITLE
Installing MarkdownLivePreview 2.3.6 never finishes (also, upgrading it doesn't complete successfully)

### ISSUE THREAD

**Issue by darkred** [math2001/MarkdownLivePreview#15]
Using  ST3 build 3126 x64 in win10 x64.
I wanted to upgrade MLP from 2.3.4 to 2.3.6.
First I got: `An error occurred while trying to upgrade MarkdownLivePreview. 
Please restart Sublime Text to finish the upgrade`

Then at ST3 restart I got some messages in console which I unfortunately I didn't keep.
Then I uninstalled it, and tried re-installing it, 
but its installation never finishes: 
it stays at `Installing package MarkdownLivePreview`.

This is what I I'm constantly getting in console now:
```
Traceback (most recent call last):
  File "package_control.loader in C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 444, in do_swap
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Kostas\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\0_package_control_loader.sublime-package'
ignored packages updated to: ["ColorHelper", "ConvertToUTF8", "MarkdownLivePreview", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'bs4' is not currently installed; installing...

```
I tried closing+restarting ST3 several times, as well as checked in Task Manager that only one SublimeText3.exe instance is running.
Nothing helped.

**Comment by darkred** [comment]
Update; after some time I tried again, it finally installed ok. 
But, I got all these in console, after the package installation:
```
Package Control: The dependency 'bs4' is not currently installed; installing...
Package Control: The dependency 'bs4' has successfully been installed or updated
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["ColorHelper", "ConvertToUTF8", "Vintage"]
reloading plugin MarkdownLivePreview.devListener
reloading plugin MarkdownLivePreview.escape_amp
reloading plugin MarkdownLivePreview.functions
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "functions in C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownLivePreview.sublime-package", line 7, in <module>
ImportError: cannot import name BeautifulSoup
reloading plugin MarkdownLivePreview.image_manager
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 107, in reload_plugin
    m = imp.reload(m)
  File "./python3.3/imp.py", line 276, in reload
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "image_manager in C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownLivePreview.sublime-package", line 8, in <module>
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "functions in C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownLivePreview.sublime-package", line 7, in <module>
ImportError: cannot import name BeautifulSoup
reloading plugin MarkdownLivePreview.MarkdownLivePreview
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "MarkdownLivePreview in C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownLivePreview.sublime-package", line 6, in <module>
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "MLPApi in C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownLivePreview.sublime-package", line 10, in <module>
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lib.pre_tables in C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownLivePreview.sublime-package", line 7, in <module>
ImportError: cannot import name BeautifulSoup
reloading plugin MarkdownLivePreview.MLPApi
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "MLPApi in C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownLivePreview.sublime-package", line 10, in <module>
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "lib.pre_tables in C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownLivePreview.sublime-package", line 7, in <module>
ImportError: cannot import name BeautifulSoup
```

After that, just to be sure, I uninstalled+reinstalled MLP, and there were no errors in console, at ll.
