### ISSUE TITLE
BUG: Dependency problem occured

### ISSUE THREAD

**Issue by ssash** [math2001/MarkdownLivePreview#27]
Hi.
I manually installed plugin in ST3130... and got this error in ST console:
<pre>
...
reloading plugin MarkdownLivePreview.image_manager
Traceback (most recent call last):
  File "/usr/lib64/sublime-text-3dev/sublime_plugin.py", line 107, in reload_plugin
    m = imp.reload(m)
  File "/usr/lib64/sublime-text-3dev/python3.3.zip/imp.py", line 276, in reload
    module.__loader__.load_module(name)
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/user/.config/sublime-text-3/Packages/MarkdownLivePreview/image_manager.py", line 8, in <module>
    from .functions import *
  File "/home/user/.config/sublime-text-3/Packages/MarkdownLivePreview/functions.py", line 8, in <module>
    from bs4 import BeautifulSoup, Comment as html_comment
ImportError: No module named 'bs4'
...
</pre>

It turns out that there are external dependencies to **[beautifulsoup4]( https://pypi.python.org/pypi/beautifulsoup4)** package.

**Comment by math2001** [comment]
You need to *satisfy the dependency*. Package Control lets you do this really easily from the command palette `Package Control: Satisfy Dependencies`.
