### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Saynah** [math2001/MarkdownLivePreview#28]
Toggle option not available. No functionality.
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 782, in run_
    return self.run()
  File "MarkdownLivePreview in /Users/marksena/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownLivePreview.sublime-package", line 115, in run
  File "MLPApi in /Users/marksena/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownLivePreview.sublime-package", line 99, in clear_cache
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/kv/grcdq8q16c397nkp8p6pj2sw0000gn/T/MarkdownLivePreviewCache.txt'
using gpu buffer for window
Unable to open /Users/marksena/Library/Application Support/Sublime Text 3/Packages/MarkdownLivePreview/.sublime/MarkdownLivePreview.sublime-settings
Unable to open /Users/marksena/Library/Application Support/Sublime Text 3/Packages/User/MarkdownLivePreview.sublime-settings
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 782, in run_
    return self.run()
  File "MarkdownLivePreview in /Users/marksena/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownLivePreview.sublime-package", line 115, in run
  File "MLPApi in /Users/marksena/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownLivePreview.sublime-package", line 99, in clear_cache
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/kv/grcdq8q16c397nkp8p6pj2sw0000gn/T/MarkdownLivePreviewCache.txt'
```

**Comment by math2001** [comment]
Does it still happen? Can you tell me exactly what you do to get this error? Does the file `/var/folders/kv/grcdq8q16c397nkp8p6pj2sw0000gn/T/MarkdownLivePreviewCache.txt` actually exists or it's a permission error (You might have to check from Finder)
