### ISSUE TITLE
Preview Window Blank. Console Output in the Comments

### ISSUE THREAD

**Issue by popecode** [math2001/MarkdownLivePreview#58]
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 509, in on_load_async
    callback.on_load_async(v)
  File "/Users/bpope/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownLivePreview.sublime-package/MarkdownLivePreview.py", line 97, in on_load_async
    md_view, preview = self.update(view)
  File "/Users/bpope/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownLivePreview.sublime-package/MarkdownLivePreview.py", line 64, in update
    show_html(view, preview)
  File "/Users/bpope/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownLivePreview.sublime-package/MLPApi.py", line 76, in show_html
    html = markdown2html(get_view_content(md_view), os.path.dirname(md_view.file_name()), md_view.settings().get('color_scheme'))
  File "/Users/bpope/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownLivePreview.sublime-package/MLPApi.py", line 40, in markdown2html
    html = '<style>\n{}\n</style>\n'.format(get_style(color_scheme))
  File "/Users/bpope/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownLivePreview.sublime-package/functions.py", line 131, in get_style
    css += pygments_from_theme(get_resource(color_scheme))
  File "/Users/bpope/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownLivePreview.sublime-package/functions.py", line 139, in get_resource
    return sublime.load_resource(resource)
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found

**Comment by ThomasAuzinger** [comment]
Same for me on Ubuntu 16.04 LTS with the latest version of Sublime Text (3170).

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 509, in on_load_async
    callback.on_load_async(v)
  File "/home/tauzinge/.config/sublime-text-3/Installed Packages/MarkdownLivePreview.sublime-package/MarkdownLivePreview.py", line 97, in on_load_async
    md_view, preview = self.update(view)
  File "/home/tauzinge/.config/sublime-text-3/Installed Packages/MarkdownLivePreview.sublime-package/MarkdownLivePreview.py", line 64, in update
    show_html(view, preview)
  File "/home/tauzinge/.config/sublime-text-3/Installed Packages/MarkdownLivePreview.sublime-package/MLPApi.py", line 76, in show_html
    html = markdown2html(get_view_content(md_view), os.path.dirname(md_view.file_name()), md_view.settings().get('color_scheme'))
  File "/home/tauzinge/.config/sublime-text-3/Installed Packages/MarkdownLivePreview.sublime-package/MLPApi.py", line 40, in markdown2html
    html = '<style>\n{}\n</style>\n'.format(get_style(color_scheme))
  File "/home/tauzinge/.config/sublime-text-3/Installed Packages/MarkdownLivePreview.sublime-package/functions.py", line 131, in get_style
    css += pygments_from_theme(get_resource(color_scheme))
  File "/home/tauzinge/.config/sublime-text-3/Installed Packages/MarkdownLivePreview.sublime-package/functions.py", line 139, in get_resource
    return sublime.load_resource(resource)
  File "/opt/sublime_text/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
```

**Comment by popecode** [comment]
I can confirm this solution works for now.

Just to note, I was using Mariana theme, which is a default.

**Comment by Some-T** [comment]
Mine is doing the same in Windows 10 after the latest update to sublime text, how can I get that info up to fix it? The error logs that is.

**Comment by math2001** [comment]
Same issue as #64, should be fixed soon.

**Comment by saltycraig** [comment]
Not working for me either on OS X 10.14.2 with ST 3.1.1 3176. Was this ever resolved?
