### ISSUE TITLE
Not exactly "no-dependency": bs4

### ISSUE THREAD

**Issue by ziembla** [math2001/MarkdownLivePreview#59]
There is a BeautifulSoup dependency in the library, at least at the moment. I get the following "bs4 not found" kind of error when "installing by git clone" (no PackageControl) on vanilla sublime text installation:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
[...] 
  File "C:\Users\XXX\AppData\Roaming\Sublime Text 3\Packages\MarkdownLivePreview\functions.py", line 8, in <module>
    from bs4 import BeautifulSoup, Comment as html_comment
ImportError: No module named 'bs4'
```

**Comment by math2001** [comment]
Is it still happening? Feel free to reopen if it does.
